// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/world"
)

type Applier struct {
	ValidateStub        func(ctx context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		ctx context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	SatisfiedStub        func(ctx context.Context) (bool, error)
	satisfiedMutex       sync.RWMutex
	satisfiedArgsForCall []struct {
		ctx context.Context
	}
	satisfiedReturns struct {
		result1 bool
		result2 error
	}
	satisfiedReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	ApplyStub        func(ctx context.Context) error
	applyMutex       sync.RWMutex
	applyArgsForCall []struct {
		ctx context.Context
	}
	applyReturns struct {
		result1 error
	}
	applyReturnsOnCall map[int]struct {
		result1 error
	}
	RequiredStub        func() world.Applier
	requiredMutex       sync.RWMutex
	requiredArgsForCall []struct{}
	requiredReturns     struct {
		result1 world.Applier
	}
	requiredReturnsOnCall map[int]struct {
		result1 world.Applier
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Applier) Validate(ctx context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		ctx context.Context
	}{ctx})
	fake.recordInvocation("Validate", []interface{}{ctx})
	fake.validateMutex.Unlock()
	if fake.ValidateStub != nil {
		return fake.ValidateStub(ctx)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.validateReturns.result1
}

func (fake *Applier) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *Applier) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return fake.validateArgsForCall[i].ctx
}

func (fake *Applier) ValidateReturns(result1 error) {
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *Applier) ValidateReturnsOnCall(i int, result1 error) {
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Applier) Satisfied(ctx context.Context) (bool, error) {
	fake.satisfiedMutex.Lock()
	ret, specificReturn := fake.satisfiedReturnsOnCall[len(fake.satisfiedArgsForCall)]
	fake.satisfiedArgsForCall = append(fake.satisfiedArgsForCall, struct {
		ctx context.Context
	}{ctx})
	fake.recordInvocation("Satisfied", []interface{}{ctx})
	fake.satisfiedMutex.Unlock()
	if fake.SatisfiedStub != nil {
		return fake.SatisfiedStub(ctx)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.satisfiedReturns.result1, fake.satisfiedReturns.result2
}

func (fake *Applier) SatisfiedCallCount() int {
	fake.satisfiedMutex.RLock()
	defer fake.satisfiedMutex.RUnlock()
	return len(fake.satisfiedArgsForCall)
}

func (fake *Applier) SatisfiedArgsForCall(i int) context.Context {
	fake.satisfiedMutex.RLock()
	defer fake.satisfiedMutex.RUnlock()
	return fake.satisfiedArgsForCall[i].ctx
}

func (fake *Applier) SatisfiedReturns(result1 bool, result2 error) {
	fake.SatisfiedStub = nil
	fake.satisfiedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *Applier) SatisfiedReturnsOnCall(i int, result1 bool, result2 error) {
	fake.SatisfiedStub = nil
	if fake.satisfiedReturnsOnCall == nil {
		fake.satisfiedReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.satisfiedReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *Applier) Apply(ctx context.Context) error {
	fake.applyMutex.Lock()
	ret, specificReturn := fake.applyReturnsOnCall[len(fake.applyArgsForCall)]
	fake.applyArgsForCall = append(fake.applyArgsForCall, struct {
		ctx context.Context
	}{ctx})
	fake.recordInvocation("Apply", []interface{}{ctx})
	fake.applyMutex.Unlock()
	if fake.ApplyStub != nil {
		return fake.ApplyStub(ctx)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.applyReturns.result1
}

func (fake *Applier) ApplyCallCount() int {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	return len(fake.applyArgsForCall)
}

func (fake *Applier) ApplyArgsForCall(i int) context.Context {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	return fake.applyArgsForCall[i].ctx
}

func (fake *Applier) ApplyReturns(result1 error) {
	fake.ApplyStub = nil
	fake.applyReturns = struct {
		result1 error
	}{result1}
}

func (fake *Applier) ApplyReturnsOnCall(i int, result1 error) {
	fake.ApplyStub = nil
	if fake.applyReturnsOnCall == nil {
		fake.applyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.applyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Applier) Required() world.Applier {
	fake.requiredMutex.Lock()
	ret, specificReturn := fake.requiredReturnsOnCall[len(fake.requiredArgsForCall)]
	fake.requiredArgsForCall = append(fake.requiredArgsForCall, struct{}{})
	fake.recordInvocation("Required", []interface{}{})
	fake.requiredMutex.Unlock()
	if fake.RequiredStub != nil {
		return fake.RequiredStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.requiredReturns.result1
}

func (fake *Applier) RequiredCallCount() int {
	fake.requiredMutex.RLock()
	defer fake.requiredMutex.RUnlock()
	return len(fake.requiredArgsForCall)
}

func (fake *Applier) RequiredReturns(result1 world.Applier) {
	fake.RequiredStub = nil
	fake.requiredReturns = struct {
		result1 world.Applier
	}{result1}
}

func (fake *Applier) RequiredReturnsOnCall(i int, result1 world.Applier) {
	fake.RequiredStub = nil
	if fake.requiredReturnsOnCall == nil {
		fake.requiredReturnsOnCall = make(map[int]struct {
			result1 world.Applier
		})
	}
	fake.requiredReturnsOnCall[i] = struct {
		result1 world.Applier
	}{result1}
}

func (fake *Applier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	fake.satisfiedMutex.RLock()
	defer fake.satisfiedMutex.RUnlock()
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	fake.requiredMutex.RLock()
	defer fake.requiredMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Applier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ world.Applier = new(Applier)
