// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/world"
)

type Configuration struct {
	ChildrenStub        func() []world.Configuration
	childrenMutex       sync.RWMutex
	childrenArgsForCall []struct{}
	childrenReturns     struct {
		result1 []world.Configuration
	}
	childrenReturnsOnCall map[int]struct {
		result1 []world.Configuration
	}
	ApplierStub        func() (world.Applier, error)
	applierMutex       sync.RWMutex
	applierArgsForCall []struct{}
	applierReturns     struct {
		result1 world.Applier
		result2 error
	}
	applierReturnsOnCall map[int]struct {
		result1 world.Applier
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Configuration) Children() []world.Configuration {
	fake.childrenMutex.Lock()
	ret, specificReturn := fake.childrenReturnsOnCall[len(fake.childrenArgsForCall)]
	fake.childrenArgsForCall = append(fake.childrenArgsForCall, struct{}{})
	fake.recordInvocation("Children", []interface{}{})
	fake.childrenMutex.Unlock()
	if fake.ChildrenStub != nil {
		return fake.ChildrenStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.childrenReturns.result1
}

func (fake *Configuration) ChildrenCallCount() int {
	fake.childrenMutex.RLock()
	defer fake.childrenMutex.RUnlock()
	return len(fake.childrenArgsForCall)
}

func (fake *Configuration) ChildrenReturns(result1 []world.Configuration) {
	fake.ChildrenStub = nil
	fake.childrenReturns = struct {
		result1 []world.Configuration
	}{result1}
}

func (fake *Configuration) ChildrenReturnsOnCall(i int, result1 []world.Configuration) {
	fake.ChildrenStub = nil
	if fake.childrenReturnsOnCall == nil {
		fake.childrenReturnsOnCall = make(map[int]struct {
			result1 []world.Configuration
		})
	}
	fake.childrenReturnsOnCall[i] = struct {
		result1 []world.Configuration
	}{result1}
}

func (fake *Configuration) Applier() (world.Applier, error) {
	fake.applierMutex.Lock()
	ret, specificReturn := fake.applierReturnsOnCall[len(fake.applierArgsForCall)]
	fake.applierArgsForCall = append(fake.applierArgsForCall, struct{}{})
	fake.recordInvocation("Applier", []interface{}{})
	fake.applierMutex.Unlock()
	if fake.ApplierStub != nil {
		return fake.ApplierStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.applierReturns.result1, fake.applierReturns.result2
}

func (fake *Configuration) ApplierCallCount() int {
	fake.applierMutex.RLock()
	defer fake.applierMutex.RUnlock()
	return len(fake.applierArgsForCall)
}

func (fake *Configuration) ApplierReturns(result1 world.Applier, result2 error) {
	fake.ApplierStub = nil
	fake.applierReturns = struct {
		result1 world.Applier
		result2 error
	}{result1, result2}
}

func (fake *Configuration) ApplierReturnsOnCall(i int, result1 world.Applier, result2 error) {
	fake.ApplierStub = nil
	if fake.applierReturnsOnCall == nil {
		fake.applierReturnsOnCall = make(map[int]struct {
			result1 world.Applier
			result2 error
		})
	}
	fake.applierReturnsOnCall[i] = struct {
		result1 world.Applier
		result2 error
	}{result1, result2}
}

func (fake *Configuration) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.childrenMutex.RLock()
	defer fake.childrenMutex.RUnlock()
	fake.applierMutex.RLock()
	defer fake.applierMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Configuration) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ world.Configuration = new(Configuration)
