// Copyright (c) 2019 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package backup

import "github.com/bborbe/world/configuration/app"

var Nova = app.BackupTarget{
	User:      "root",
	Host:      "nova.hm.benjamin-borbe.de",
	IP:        "172.16.90.16",
	Port:      22,
	Directory: "/",
	Excludes: []string{
		"._*",
		".AppleDouble",
		".com.apple.timemachine.donotpresent",
		".DocumentRevisions-V100",
		".fseventsd",
		".HFS+ Private Directory Data",
		".metadata_never_index",
		".Spotlight-V100",
		".Trash",
		".Trashes",
		".VolumeIcon.icns",
		"/.com.apple.NetBootX",
		"/.fseventsd",
		"/.hotfiles.btree",
		"/.journal_info_block",
		"/.journal",
		"/.MobileBackups",
		"/.vol/*",
		"/Applications/Adobe/AdobePatchFiles/*",
		"/Applications/Diablo III/*",
		"/Applications/Epic Games Launcher.app/*",
		"/Applications/StarCraft II/*",
		"/Applications/World of Warcraft/*",
		"/automount",
		"/Backups.backupdb",
		"/cores",
		"/dev/*",
		"/Library/Caches/*",
		"/Library/Logs/*",
		"/lost+found",
		"/net",
		"/Network",
		"/opt/local/var/macports/*",
		"/opt/local/var/squid/cache/*",
		"/private/*",
		"/stuff/*",
		"/System/*",
		"/TheVolumeSettingsFolder",
		"/Users/bborbe/.docker/machine/machines/*",
		"/Users/bborbe/.glide/cache/*",
		"/Users/bborbe/.kube/cache/*",
		"/Users/bborbe/.kube/http-cache/*",
		"/Users/bborbe/.m2/repository/*",
		"/Users/bborbe/.vagrant.d/*",
		"/Users/bborbe/.vagrant.d/cache/*",
		"/Users/bborbe/Downloads/*",
		"/Users/bborbe/Dropbox/.dropbox.cache/*",
		"/Users/bborbe/Library/Application Support/Chat/Cache/*",
		"/Users/bborbe/Library/Application Support/MobileSync/Backup/*",
		"/Users/bborbe/Library/Application Support/Spotify/PersistentCache/*",
		"/Users/bborbe/Library/Application Support/Steam/steamapps/common/*",
		"/Users/bborbe/Library/Caches/*",
		"/Users/bborbe/Library/Containers/com.apple.mail/Data/DataVaults",
		"/Users/bborbe/Library/Containers/com.docker.docker",
		"/Users/bborbe/Library/iTunes/iPad Software Updates/*",
		"/Users/bborbe/Library/iTunes/iPhone Carrier Support/*",
		"/Users/bborbe/Library/iTunes/iPhone Software Updates/*",
		"/Users/bborbe/Library/iTunes/iPod Software Updates/*",
		"/Users/bborbe/Library/Mobile Documents*",
		"/Users/bborbe/Music/iTunes/iTunes Media/Podcasts/*",
		"/Users/bborbe/Pictures/20*",
		"/Users/bborbe/Pictures/Aperture Library.aplibrary/Thumbnails/*",
		"/Users/bborbe/Pictures/Tethered/*",
		"/Users/bborbe/VirtualBox VMs/*",
		"/Users/jana/.vagrant.d/*",
		"/Users/jana/.vagrant.d/cache/*",
		"/Users/jana/Downloads/*",
		"/Users/jana/Library/Application Support/MobileSync/Backup/*",
		"/Users/jana/Library/Application Support/Steam/steamapps/common/*",
		"/Users/jana/Library/Caches/*",
		"/Users/jana/Library/Containers/com.apple.mail/Data/DataVaults",
		"/Users/jana/Library/iTunes/iPad Software Updates/*",
		"/Users/jana/Library/iTunes/iPhone Carrier Support/*",
		"/Users/jana/Library/iTunes/iPhone Software Updates/*",
		"/Users/jana/Library/iTunes/iPod Software Updates/*",
		"/Users/jana/Library/Logs/*",
		"/Users/jana/Library/Mobile Documents*",
		"/Users/jana/VirtualBox VMs/*",
		"/Users/Shared/Epic Games/*",
		"/Users/Shared/Lightroom/Lightroom Catalog Previews.lrdata/*",
		"/Users/Shared/Lightroom/Lightroom Catalog-2 Previews.lrdata/*",
		"/Users/Shared/UnrealEngine/*",
		"/Volumes/*",
		"Saved Application State",
		"/Users/bborbe/Documents/workspaces/go/pkg/*",
	},
}
